name: seven_double_client
description: Native Android and Windows client for Seven Double.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: HarmonyOS Sans SC
      fonts:
        - asset: assets/fonts/HarmonyOS_Sans_SC_Regular.ttf
          weight: 400
        - asset: assets/fonts/HarmonyOS_Sans_SC_Medium.ttf
          weight: 500
        - asset: assets/fonts/HarmonyOS_Sans_SC_Bold.ttf
          weight: 700
